name: ParadigmLeap
favicon: null
layout_spectrum: 0.74038
typography_spectrum: 0.9556992000434548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#da0e36'
    - '#5c0416'
    - '#880821'
    - '#33020c'
  brandStrength: 0.5
  lightness: 0.6875889478251338
  saturation: 0.17371966573409736
  rhythmicContrast: 0.3224535631015897
purpose: []
